### ISSUE TITLE
Computing resource?

### ISSUE THREAD

**Issue by codenewww** [Yan-Xia/Text2Loc#3]
Thanks for your code!
Could you please specify the computational resources used for your experiments? Specifically, what type and number of GPUs were employed?
If I only have one RTX 3090, can I finish the experiment?

**Comment by anslt** [comment]
If you want to train following the instructions, you only need 1 24-48GB GPU.
I cannot guarantee whether 1 RTX 3090 finish the experiment. if it is not successful, you can decrease the batch size in the training process (e.g. from 64 to 56/48).
