### ISSUE TITLE
Questions about robustness analysis

### ISSUE THREAD

**Issue by kcjms2000** [Yan-Xia/Text2Loc#4]
Dear authors,
Thanks for your great work!
I'm interested in the robustness analysis about the model. I tried a few times to change sentence format in the text query (only change one sentence), but it seems the performance doesn't drop too much. So I wonder how to modify the sentence to analyze the robustness? 
Many thanks for your help in advance!

**Comment by anslt** [comment]
Instead of changing the format, it would be better to change the context.
For example, south => north, green => gray, pole => smallpole.

**Comment by kcjms2000** [comment]
Thanks a lot for your reply !
