### ISSUE TITLE
files containing textual descriptions

### ISSUE THREAD

**Issue by Rabbia-Hassan** [Yan-Xia/Text2Loc#5]
hello,
thank you for the interesting work.
I can not figure out the files containing the textual descriptions, can you please provide them ? Or pin point that where are they stored? Thanks a lot.

**Comment by Rabbia-Hassan** [comment]
But these .pickle files don't contain the textual descriptions, rather they contain some coordinates or indices like this. I am looking for the fact that, where are the textual descriptions being stored ?
![image](https://github.com/user-attachments/assets/5e575e77-28c7-4785-9e59-488dccfc3ca1)

**Comment by anslt** [comment]
You should look "https://github.com/Yan-Xia/Text2Loc/blob/main/datapreparation/kitti360pose/imports.py" to see what the class Pose looks like. The data[0] in your descriptions is actually an instance of class Pose.

**Comment by Rabbia-Hassan** [comment]
thank you for the clarification.
You are right. Descriptions can be accessed this way.
I am assuming that these are the descriptions corresponding to few of the query points tha were rendomly sampled from the point cloud file 2013_05_28_drive_0000_sync. I am wondering how can we find out that which exactly is the point whose description is this. Like if there is a way to find out the points corresponding to these descritions for better visualization.
![image](https://github.com/user-attachments/assets/ad5b3904-1144-47fe-8e9a-db2e7b45da11)

**Comment by anslt** [comment]
Please check "https://github.com/Yan-Xia/Text2Loc/blob/main/datapreparation/kitti360pose/imports.py"
