### ISSUE TITLE
evaluation script is not correct 

### ISSUE THREAD

**Issue by PrashantSukkumar2** [Yan-Xia/Text2Loc#6]
Hy !
thank you for sharing such an interesting piece of work.
There is some problem/bug in your evaluation/pipeline script. The process gets killed when script is halfway through the evaluation.  It doesnt complete the evaluation, neither for the val nor test split. 
Although thr gpu utlization on my machine hardly remains 40 %. So it has nothing to do with the gpu or other resource exhaussion related stuff.
Please guide.
Thanks
![image](https://github.com/user-attachments/assets/c2514d6f-f5ad-4a01-aa97-224fa615c093)

**Comment by anslt** [comment]
Would you check your GPU memory usage or memory usage? Since I cannot see any error message in your screen but only the process is killed.

**Comment by PrashantSukkumar2** [comment]
i have checked both of them already, gpu memory was only being used maximum by 60 percent, and cpu memory and ram usage was also not an issue. Also, on the same machine training worked absolutely fined. But testing is not working.

**Comment by anslt** [comment]
Thank you for your response. We checked the codes on multiple servers and it worked fine. I would very much appreciate it if you could offer more messages about the problem. The message in the captured image is very similar to the Linux out-of-memory issue as it has only a "Killed" message. Maybe you can increase your memory limitation to check whether can fix the problem.

**Comment by PrashantSukkumar2** [comment]
okay, but which memory are you specifically referring to here? because I have check again , GPU memory is not a problem at all. I kept monitoring the gpu consumption and it was below 50 percent all the time. However, please guide me about the possible issues, like can it be due to RAM or something ?

**Comment by anslt** [comment]
Here is my process. I think the problem comes from the full SWAP, as it may cause OOM killer which is the same error messages compared to your first screenshot. It is very strange that when your RAM is not full but your SWAP is full. Would you please empty your SWAP and then run the code once more? As we don't have such problem, it would be helpful for you to find which part of our code makes this situation if you still have the problem for the evaluation.
![1726397803135](https://github.com/user-attachments/assets/c4c93025-7446-4260-ae88-8194e0009cdf)

**Comment by PrashantSukkumar2** [comment]
you are right. But I think I can not make the swap empty as it is a multi user shared server. And other people are using it as well. I think I even dont have rights to clear the swap memory.
Also, other user processes (of other users) are running absolutely fine, if swap memory is an issue then it should be bothering the other user's processes as well.  But do you still think that swap memory can be the possible underlying issue for this problem ?

**Comment by anslt** [comment]
I guess the problem comes from the memory issue.
